### PR TITLE
Support NOOP actions

### PR DESCRIPTION
**Pull request by artnez**
For actions that only call other actions.

### CODE REVIEW

**Comment by artnez** [comment]
Nevermind. Found a better way.

**Comment by artnez** [comment]
@steadicat In case you're curious why I even considered this (it might come up again):

``` javascript
// somewhere.js
window.addEventListener('popstate', function(event) {
  actions.setPageURL(...);
});

// actions.js
export function navigate(store, actions, url) {
  window.history.pushState(null, url); // synchronous!
  return store;
}

export function setPageURL(store, actions, pageURL) {
  return {...store, pageURL};
}
```

**Comment by artnez** [comment]
So the issue is a synchronous function call sitting between two action calls.

```
Action1 -> SyncFunction -> Action2
               ^
               |
         We lose control.
```

However if `Action1` returns null/undefined and becomes a NOOP action, we're ok.

**Comment by steadicat** [comment]
The warning about actions calling other actions synchronously (#3) should
catch this.

**Pull request closed without merging**
